kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plugin-jam-system-postgres-data
  namespace: plugin-jam-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
