spring:
  datasource:
    url: "jdbc:postgresql://localhost/my_database"
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create

---

spring:
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"
        hbm2ddl: create
  datasource:
    url: "jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1"
    username: user
    password: password
    driver-class-name: "org.h2.Driver"
  config:
    activate:
      on-profile: local

  security:
    user:
      name: "test"
      password: "test"
